[workspace]
members = [
    "rkubectl",
    "api_server",
    "rkubelet",
    "resources",
    "controllers",
    "scheduler",
    "rkube-proxy",
]

[patch.crates-io]
bollard = { git = 'https://github.com/y-young/bollard' }
