unstable_features = true
imports_granularity = "Crate"
match_block_trailing_comma = true
normalize_comments = true
condense_wildcard_suffixes = true
struct_lit_single_line = false
group_imports = "StdExternalCrate"
