[package]
name = "controllers"
version = "0.1.0"
edition = "2021"

[[example]]
name = "dummy-controller"

[[bin]]
name = "endpoints-controller"
path = "src/endpoints/main.rs"

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
resources = { path = "../resources" }
anyhow = { version = "1.0.56", features = ["backtrace"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio-tungstenite = "0.17.1"
tracing = "0.1.32"
tracing-subscriber = "0.3.10"
dashmap = "5.2.0"
lazy_static = "1.4.0"
dotenv = "0.15.0"
