apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  containers:
    - name: httpd
      image: httpd:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
