apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
    name: CPU
    target:
      averageUtilization: 50