apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: server
spec:
  nodeSelector:
    gpu: nvidia
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
