apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: server
spec:
  replicas: 3
  selector:
    app: server
  template:
    metadata:
      name: nginx
      labels:
        app: server
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80